name: Subir Para AWS

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    build:
        name: Build da Lambda
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout do repositório
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'
      
            - name: Install dependencies
              run: |
                cd projeto
                npm install
      
            - name: Criar zip
              run: |
                cd projeto
                zip -r ../lambda.zip .
